services:
  db:
    image: postgres:alpine
    container_name: linter-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - snippet-net

  linting-service:
    build: .
    container_name: linting-service
    ports:
      - "${API_PORT}:8081"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - snippet-net

networks:
  snippet-net:
    external: true

volumes:
  db:
  gradle-cache: