services:
  db:
    image: postgres:alpine
    container_name: linter-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - snippet-net

  linting-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: linting-service
    ports:
      - "${API_PORT}:8082"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - snippet-net

networks:
  snippet-net:
    external: true

volumes:
  db:
  gradle-cache: