services:
  linting-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: linting-service
    ports:
      - "${API_PORT}:8082"
    env_file:
      - .env
    networks:
      - snippet-net

networks:
  snippet-net:
    external: true

volumes:
  db:
  gradle-cache: